// These types would be generated by the Apollo looing from schema in a real application

export interface Employee {
  id: string;
  name: string;
  gender: string;
  department: string;
  position: string;
  email: string;
  dateOfBirth: string;
  dateJoined: string;
  status: string;
  avatar: string;
}

export interface Leave {
  id: string;
  employeeId: string;
  leaveType: string;
  startDate: string;
  endDate: string;  
}

export interface EmployeeOnLeave {
  id: string;
  name: string;
  department: string;
  position: string;
  avatar: string;
  leaveType: string;
  startDate: string;
  endDate: string;
}

export interface DepartmentBreakdown {
  department: string;
  count: number;
}

export interface TeamOverview {
  totalEmployees: number;
  activeEmployees: number;
  employeesOnLeave: number;
  departmentBreakdown: DepartmentBreakdown[];
}

export interface Query {
  employeesOnLeave: EmployeeOnLeave[];
  birthdaysThisWeek: Employee[];
  teamOverview: TeamOverview;
}
